spring:
  redis:
    host: localhost
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
  datasource:
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
          username: root
          password: root
        slave_1:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://10.251.101.175:18923/dlmhdb?currentSchema=dlmhcfg&stringtype=unspecified
          username: agent
          password: eqh1RCBGd%Oqnh2m
        slave_2:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://49.74.219.78:3307/uni_api_mgr?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: tdxx
          password: tdxxnewyear2013
      lazy: true
      # 多数据源选择算法，默认轮询
      # strategy: com.baomidou.dynamic.datasource.strategy.RandomDynamicDataSourceStrategy
      druid:
        # 初始连接数
        initial-size: 5
        # 最小连接池数量
        min-idle: 10
        # 最大连接池数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 配置检测连接是否有效
        validation-query: SELECT 1
        # 默认 true 为 true 时 validationQuery 必须设为非空字符串
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat:
          # 慢sql记录
          log-slow-sql: true
          slow-sql-millis: 6000
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto # 主键类型
  mapper-locations: classpath:com/betty/practice/mapper/*.xml
  type-aliases-package: com.betty.practice.bean


