server:
  port: 88
spring:
  profiles:
    active: dev
  application:
    name: practice
  main:
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    dynamic:
      lazy: true
      # 多数据源选择算法，默认轮询
      # strategy: com.baomidou.dynamic.datasource.strategy.RandomDynamicDataSourceStrategy
      druid:
        # 初始连接数
        initial-size: 5
        # 最小连接池数量
        min-idle: 10
        # 最大连接池数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 配置检测连接是否有效
        validation-query: SELECT 1
        # 默认 true 为 true 时 validationQuery 必须设为非空字符串
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat:
          # 慢sql记录
          log-slow-sql: true
          slow-sql-millis: 6000

async:
  executor:
    thread:
      core-pool-size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name-prefix: async-service-

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto # 主键类型
  mapper-locations: classpath:com/betty/practice/mapper/xml/*.xml
  type-aliases-package: com.betty.practice.bean

upload:
  path: D:\Upload\practice\file\
