server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: practice

async:
  executor:
    thread:
      core-pool-size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name-prefix: async-service-
